### ISSUE TITLE
Redirect invalid user error to custom page

### ISSUE THREAD

**Issue by baur** [nbayramberdiyev/grafana-generic-oauth#2]
Is it possible redirect invalid user error to custom page? like **you're not registered** or **access is denied**. Because autologin excludes wrong user/password case ...

**Comment by nbayramberdiyev** [comment]
In `auth_url`, `token_url` and `api_url` endpoints, you're already checking if the user is valid and authenticated in your application. If not you can make a redirect to a custom page:
```
header('Location: /custom-page');
die();
```
Or you can simply response with a custom message and a 401 status code:
```
header('HTTP/1.1 401 Unauthorized');
include '401.php';
die();
```

**Comment by nbayramberdiyev** [comment]
In `auth_url`, `token_url` and `api_url` endpoints, you're already checking if the user is valid and authenticated in your application. If not you can make a redirect to a custom page:
```
header('Location: /custom-page');
die();
```
And optionally you can response with a 401 status code in your `/custom-page` page:
```
header('HTTP/1.1 401 Unauthorized');
...
```

**Comment by baur** [comment]
Ok

**Comment by baur** [comment]
```
header('Location: /custom-page');
die();
```
it works

> If you want users login automatically, you'll need to place custom.js in /usr/share/grafana/public/build/index.html

now, how to logout, I'd like to login in as admin )))


PS: full path to **index.html** is **grafana/public/views/index.html** not build/index.html

**Comment by nbayramberdiyev** [comment]
After a user signs out in your application, make a redirect to Grafana's logout page:
```
header('Location: https://your-grafana-app.com/logout');
die();
```
Then, edit your `grafana.ini` file and set [`signout_redirect_url`](https://grafana.com/docs/grafana/latest/auth/overview/#url-redirect-after-signing-out) as the login page of your application:
```
signout_redirect_url = https://your-app.com/login-page
```
