### ISSUE TITLE
client id and secret

### ISSUE THREAD

**Issue by DeepthiPrapulla** [nbayramberdiyev/grafana-generic-oauth#4]
Hi,

What is Client ID and Client Secret mentioned in your code. How to configure them

**Comment by nbayramberdiyev** [comment]
Client ID is administrator _username_ and Client Secret is administrator _password_ which both defaults to **admin**.

**Comment by DeepthiPrapulla** [comment]
I have a web application which uses PHP. It has its own  functionality to authenticate login. I need to navigate to grafana with same login. Shall I go ahead with trying your implementation? I am not sure if i am on right track

**Comment by nbayramberdiyev** [comment]
This is the implementation of generic OAuth2 in Grafana. You also need to create organization/users (using admin credentials). You can assign them the same email and password that you used in your own application.
